### PR TITLE
TypeScript - Fix handling of union types

### LINKED ISSUE #8: type definitions don't work for union types
```ts
arrify(Boolean() ? [1, 2] : 3);
```

The above returns the type `(number | number[])[]`. This doesn't match the runtime value of `number[]`

### LINKED ISSUE #10: type definitions don't work for tuple types
```ts
declare let tuple: [number, string];

const arrified = arrify(tuple);
arrified.push(1);
arrified[0] = 'foo'
```

Since tuples are arrays, they are returned as is. The type declarations however widen the type to a regular (mutable) array type.  Both mutations above should not be allowed.

### PR DESCRIPTION
**Pull request by BendingBender**
Original patch proposed in #9 by @callmehiphop. This is an extension that handles all possible union type combinations. Thank you!

Fixes #8
Fixes #10

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -23,12 +23,18 @@ arrify(undefined);
...
-declare function arrify<ValueType>(value: ReadonlyArray<ValueType>): ReadonlyArray<ValueType>;
-declare function arrify<ValueType>(value: Iterable<ValueType>): ValueType[];
-declare function arrify<ValueType>(value: ValueType): [ValueType];
+declare function arrify<ValueType>(
+	value: ValueType
+): ValueType extends (null | undefined)
+	? []
+	: ValueType extends string
+	? [string]
+	: ValueType extends (infer T)[]
```
Comment (ajafff) [inline index.d.ts]: If you change this to `: ValueType extends ReadonlyArray<unknown> ? ValueType : ...` you also fix #10 
Note that this one condition covers mutable and readonly arrays as well as tuples.

**Review by ajafff — APPROVED** [review]
